import Head from "next/head";
import Image from "next/image";
import formImage from "../../public/form.png";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";

export default function Home() {
  // Router

  const router = useRouter();

  // Formik logics

  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Hungary",
      terms: "",
    },

    // Validate form

    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less")
        .required("Required"),
      email: Yup.string().email("Invalid email").required("Required"),
      terms: Yup.array().required("ToS must be checked"),
    }),

    // Submit form

    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-1/2 font-latoRegular"
        >
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-bold">Let's get started 😎</h1>
            <p className="text-lg text-gray-500">
              Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.
            </p>
            <div className="mt-6">
              {}
              <div className="pb-4">
                <label
                  className={`block font-bold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500 focus:outline-none"
                  type="text"
                  name="name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  placeholder="Enter your name"
                  onBlur={formik.handleBlur}
                />
              </div>
            </div>
            <div className="mt-6">
              {}
              <div className="pb-4">
                <label
                  className={`block font-bold text-sm pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500 focus:outline-none"
                  type="email"
                  name="email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  placeholder="Enter your e-mail"
                  onBlur={formik.handleBlur}
                />
              </div>
            </div>
            <div className="mt-6">
              {}
              <div className="pb-4">
                <label
                  className="block font-bold text-sm pb-2"
                  htmlFor="country"
                >
                  Country
                </label>
                <select
                  name="country"
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500 focus:outline-none"
                  value={formik.values.country}
                  onChange={formik.handleChange}
                >
                  <option>Hungary</option>
                  <option>United States</option>
                  <option>Germany</option>
                  <option>Australia</option>
                </select>
              </div>
            </div>
            <div className="mt-6">
              {}
              <div className="pb-4">
                <label
                  className={`block font-bold text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms of Service"}
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                    className="h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500 focus:outline-none"
                  />
                  <p className="text-sm font-bold text-gray-500">
                    I agree to the Terms and Service that my data will be taken
                    and sold.
                  </p>
                </div>
              </div>
            </div>
            <button
              type="submit"
              className="bg-teal-500 font-bold text-sm text-white py-3 mt-6 rounded-lg w-full"
            >
              Start learning today!
            </button>
          </div>
          <div className="flex-1 relative">
            <Image
              alt="form-learn"
              src={formImage}
              fill
              priority
              className="object-cover rounded-lg"
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
